/softhand_vision_based_grasp_marker_from_human_node:
   ros__parameters:
      'grasp_time': 1
      'release_time': 1
      
      'bend_angle_array_point0': [0.0, 41.0, 270.0, 35.0, 0.0]  #in degrees, range:[0, 300]
      'wave_angle_array_point0': [40.0, 4.35, 2.8, 32.0, 10.0]   # range:[-150, 150]
      'bend_angle_array_point1': [110.0, 160.0, 170.0, 140.0, 130.0]   
      'wave_angle_array_point1': [40.0, 4.35, 2.8, 32.0, 10.0]    

      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [20.0, 20.0, 20.0, 20.0, 20.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
