/softhand_grasp_node:
   ros__parameters:
      'grasp_time': 15
      'release_time': 30
      
      'bend_angle_array_point0': [58.0, 41.0, 270.0, 35.0, 41.0]  #in degrees, range:[0, 300]
      'wave_angle_array_point0': [0.0, 4.35, 2.8, 26.0, 1.0]   # range:[-150, 150]
      'bend_angle_array_point1': [180.0, 180.0, 140.0, 170.0, 180.0]     #both Jello fail
      'wave_angle_array_point1': [0.0, 4.35, 2.8, 26.0, 1.0]    

      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [20.0, 20.0, 20.0, 20.0, 20.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
