/softhand_manipulation_node:
   ros__parameters:

      'bend_angle_array_point0': [0.0, 41.0, 270.0, 35.0, 0.0]  #in degrees, range:[0, 300]
      'bend_angle_array_limit': [110.0, 155.0, 185.0, 135.0, 100.0]

      'wave_angle_array_point0': [40.0, 4.35, 2.8, 32.0, 10.0]   # range:[-150, 150]
      'wave_angle_array_limit1': [-60.0, 70.0, -75.0, 70.0, -85.0]
      'wave_angle_array_limit2': [130.0, -40.0, 70.0, -50.0, 70.0]

      'bend_speed_array_preset': [0.5, 0.5, 0.5, 0.5, 0.5]  #in degrees/sec, range:[0-684]
      'wave_speed_array_preset': [0.5, 0.5, 0.5, 0.5, 0.5]  

      'K_P' : 0.3
      'K_I' : 0.005
      'K_D' : 0.01