/softhand_grasp_small_objects_node:
   ros__parameters:
      'grasp_time1': 22
      'grasp_time2': 9
      #'release_time1': 22    #strawberry and banana
      'release_time1': 30    #for eggs pick and place
      'release_time2': 8

      
      'bend_angle_array_point0': [58.0, 41.0, 270.0, 35.0, 41.0]  # in degrees, range:[0, 300]
      'wave_angle_array_point0': [0.0, 4.35, 2.8, 26.0, 1.0]   # range:[-150, 150]     
      #'bend_angle_array_point1': [58.0, 41.0, 270.0, 35.0, 41.0]       # strawberry, banana
      #'bend_angle_array_point2': [162.0, 151.0, 160.0, 115.0, 131.0]    # strawberry, banana
      'bend_angle_array_point1': [58.0, 41.0, 270.0, 35.0, 41.0]    # egg
      'bend_angle_array_point2': [162.0, 156.0, 165.0, 115.0, 131.0]    # egg
      'wave_angle_array_point1': [0.0, 4.35, 2.8, 26.0, 1.0]    


      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [8.0, 8.0, 8.0, 8.0, 8.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
