/softhand_grasp_multiobjects_node:
   ros__parameters:
      #'grasp_time1': 32    #vertical+lateral
      #'grasp_time2': 36
      #'release_time1': 36
      #'release_time2': 36
      
      'grasp_time1': 36    #lateral+lateral
      'grasp_time2': 32
      'release_time1': 32
      'release_time2': 6

      'bend_angle_array_point0': [58.0, 41.0, 270.0, 35.0, 41.0]  #in degrees, range:[0, 300]
      'wave_angle_array_point0': [10.0, 4.35, 2.8, 26.0, 10.0]   # range:[-150, 150]
      #'bend_angle_array_point1': [128.0, 111.0, 200.0, 105.0, 131.0]    # tennis ball
      #'bend_angle_array_point1': [123.0, 106.0, 205.0, 100.0, 126.0]    # orange
      #'bend_angle_array_point1': [128.0, 111.0, 200.0, 95.0, 100.0]    # pear
      #'bend_angle_array_point1': [118.0, 101.0, 210.0, 95.0, 121.0]    # apple
      #'bend_angle_array_point1': [148.0, 131.0, 180.0, 105.0, 131.0]    # small glass bottle
      #'bend_angle_array_point1': [162.0, 151.0, 160.0, 115.0, 131.0]    # banana, tilt,false
      #'bend_angle_array_point1': [148.0, 141.0, 170.0, 35.0, 41.0]    # two fruits
      #'bend_angle_array_point2': [148.0, 141.0, 170.0, 160.0, 206.0]
      'bend_angle_array_point1': [208.0, 205.0, 125.0, 40.0, 46.0]    # two coke can, lateral
      'bend_angle_array_point2': [208.0, 205.0, 125.0, 215.0, 260.0]
      #'bend_angle_array_point1': [148.0, 131.0, 180.0, 125.0, 151.0]
      'wave_angle_array_point1': [10.0, 4.35, 2.8, 80.0, 50.0]    



/softhand_fingers_move2points_node:
   ros__parameters:
      'bend_angle_array_point0': [50.0, 64.0, 242.0, 55.0, 66.0]  #grasp in degrees, range:[0, 300]
#      'bend_angle_array_point0': [70.0, 70.0, 240.0, 60.0, 70.0]
      'bend_angle_array_point1': [150.0, 150.0, 165.0, 135.0, 155.0]    #rotate
#     'bend_angle_array_point1': [140.0, 104.0, 195.0, 100.0, 110.0]    #grasp 
      'wave_angle_array_point0': [0.0, 5.0, 3.5, 7.8, 1.7]   # range:[-150, 150]
      'wave_angle_array_point1': [-20.0, 65.0, 63.5, 67.8, 61.7]
      'wave_angle_array_point2': [15.0, -55.0, -56.5, -52.2, -59.3]
#      'wave_angle_array_point0': [0.0, 0.0, 0.0, 0.0, 0.0]   # range:[-150, 150]
#      'wave_angle_array_point1': [90.0, 90.0, 90.0, 90.0, 90.0]
#      'wave_angle_array_point2': [-90.0, -90.0, -90.0, -90.0, -90.0]
      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [30.0, 30.0, 30.0, 30.0, 30.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
