/softhand_grasp_node:
   ros__parameters:
      'bend_angle_array': [200.0, 90.0, 90.0, 90.0, 200.0]  #in degrees, range:[0, 300]
      'wave_angle_array': [0.0, 0.0, 0.0, 0.0, 0.0]   # range:[-150, 150]
      
      
/softhand_fingers_move2points_node:
   ros__parameters:
      'bend_angle_array_point0': [0.0, 0.0, 0.0, 0.0, 0.0]  #in degrees, range:[0, 300]
      'bend_angle_array_point1': [150.0, 200.0, 200.0, 200.0, 200.0]
      'wave_angle_array_point0': [0.0, 0.0, 0.0, 0.0, 0.0]   # range:[-150, 150]
      'wave_angle_array_point1': [90.0, 90.0, 90.0, 90.0, 90.0]
      'wave_angle_array_point2': [-90.0, -90.0, -90.0, -90.0, -90.0]
      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [30.0, 30.0, 30.0, 30.0, 30.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]   
