/softhand_grasp_node:
   ros__parameters:
      'grasp_time': 8
      'release_time': 600
      
      'bend_angle_array_point0': [58.0, 41.0, 270.0, 35.0, 41.0]  #in degrees, range:[0, 300]
      'wave_angle_array_point0': [40.0, 4.35, 2.8, 32.0, 10.0]   # range:[-150, 150]
      #'bend_angle_array_point1': [170.0, 140.0, 185.0, 185.0, 200.0]  
      'bend_angle_array_point1': [180.0, 125.0, 200.0, 140.0, 160.0] 
      'wave_angle_array_point1': [40.0, 4.35, 2.8, 52.0, 10.0] 

      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [20.0, 20.0, 20.0, 20.0, 20.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
