/softhand_grasp_gesture_test_node:
   ros__parameters:
      'grasp_time': 8
      'release_time': 10
      
      'bend_angle_array_point0': [0.0, 41.0, 270.0, 35.0, 0.0]  #in degrees, range:[0, 300]
      'wave_angle_array_point0': [40.0, 4.35, 2.8, 32.0, 10.0]   # range:[-150, 150]
      #'bend_angle_array_point1': [110.0, 160.0, 170.0, 140.0, 130.0]   #regular grasp
      #'bend_angle_array_point1': [95.0, 135.0, 195.0, 115.0, 110.0]   #5-finger pinch grasp
      #'bend_angle_array_point1': [120.0, 170.0, 160.0, 155.0, 150.0]   #5-finger power grasp
      'bend_angle_array_point1': [120.0, 170.0, 160.0, 35.0, 0.0]   #3-finger pinch grasp
      'wave_angle_array_point1': [40.0, 4.35, 2.8, 32.0, 10.0]   
      
/softhand_setspeed_clientnode:
   ros__parameters:
      'bend_speed_array': [20.0, 20.0, 20.0, 20.0, 20.0]  #in degrees/sec, range:[0-684]
      'wave_speed_array': [15.0, 15.0, 15.0, 15.0, 15.0]  
